/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.GOVTRepresentative;

import Business.Enterprise.Enterprise;
import Business.HealthMinistryRepresentative.Representative;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.RationRequest;
import Business.WorkQueue.VolunteerRequest;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rtspi
 */
public class ManageVolunteerRequestsRepresentativeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form createUnitsRepresentativeJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Organization organization;
    private OrganizationDirectory orgDir;
    public ManageVolunteerRequestsRepresentativeJPanel(JPanel userProcessContainer, Enterprise enterprise,UserAccount account,OrganizationDirectory orgDir,Organization organization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.orgDir = orgDir;
        this.userAccount = account;
        this.organization = organization;
        populateTable();
    }
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) tblRequestHistory.getModel();
         model.setRowCount(0);
             Representative representative =organization.getRepresentativeDirectory().findUserByUserName(userAccount.getUsername());
           for(VolunteerRequest req : representative.getVolunteerRequestDirectory().getVolunteerRequestList()){
               
            Object[] row = new Object[5];
            row[0] = req.getRequestName();
            row[1] = req;
            row[2] = req.getUnits();
            row[3] = req.getDate();
            row[4] = req.getStatus();
            model.addRow(row);
        }   
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRequestHistory = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnAccept = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();
        btnComplete = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        tblRequestHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Request Name", "Type of Volunteer", "Number of Volunteers", "Request Date", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblRequestHistory);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel2.setText("Manage Volunteers Requests");

        btnAccept.setBackground(new java.awt.Color(255, 255, 255));
        btnAccept.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnAccept.setForeground(new java.awt.Color(0, 255, 204));
        btnAccept.setText("Accept Request");
        btnAccept.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAccept.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAcceptMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAcceptMouseExited(evt);
            }
        });
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });

        btnReject.setBackground(new java.awt.Color(255, 255, 255));
        btnReject.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnReject.setForeground(new java.awt.Color(0, 255, 204));
        btnReject.setText("Reject Request");
        btnReject.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRejectMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRejectMouseExited(evt);
            }
        });
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });

        btnComplete.setBackground(new java.awt.Color(255, 255, 255));
        btnComplete.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnComplete.setForeground(new java.awt.Color(0, 255, 204));
        btnComplete.setText("Complete Request");
        btnComplete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnComplete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCompleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCompleteMouseExited(evt);
            }
        });
        btnComplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(274, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(174, 174, 174)
                                .addComponent(jLabel2))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnAccept)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnReject))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(222, 222, 222))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnComplete)
                        .addGap(471, 471, 471))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel2)
                .addGap(58, 58, 58)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReject)
                    .addComponent(btnAccept))
                .addGap(86, 86, 86)
                .addComponent(btnComplete, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(264, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcceptMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcceptMouseEntered
        // TODO add your handling code here:
        btnAccept.setBackground(new Color(0,255,204));
        btnAccept.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btnAcceptMouseEntered

    private void btnAcceptMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcceptMouseExited
        // TODO add your handling code here:
        btnAccept.setForeground(new Color(0,255,204));
        btnAccept.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnAcceptMouseExited

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        // TODO add your handling code here:
        int row = tblRequestHistory.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        VolunteerRequest fReq=(VolunteerRequest)tblRequestHistory.getValueAt(row, 1);
        if(fReq.getStatus().equalsIgnoreCase("Rejected")){
            JOptionPane.showMessageDialog(null, "Request is rejected already", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else if(fReq.getStatus().equalsIgnoreCase("Accepted")){
            JOptionPane.showMessageDialog(null, "Request is already accepted", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else if(fReq.getStatus().equalsIgnoreCase("Processed - Sent to Volunteering Head")){
            JOptionPane.showMessageDialog(null, "Request is processed already", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else if(fReq.getStatus().equalsIgnoreCase("Completed")){
            JOptionPane.showMessageDialog(null, "Request is completed already", "Warning", JOptionPane.WARNING_MESSAGE);

        }

        else{

            //        FinanceRequest fReq=(FinanceRequest)tblRequests.getValueAt(row, 1);
            fReq.setStatus("Accepted");
            JOptionPane.showMessageDialog(null, "Request Accepted successfully!!!");
        }
        populateTable();
    }//GEN-LAST:event_btnAcceptActionPerformed

    private void btnRejectMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRejectMouseEntered
        // TODO add your handling code here:
        btnReject.setBackground(new Color(0,255,204));
        btnReject.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btnRejectMouseEntered

    private void btnRejectMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRejectMouseExited
        // TODO add your handling code here:
        btnReject.setForeground(new Color(0,255,204));
        btnReject.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnRejectMouseExited

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
        // TODO add your handling code here:
        int row = tblRequestHistory.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        VolunteerRequest fReq=(VolunteerRequest)tblRequestHistory.getValueAt(row, 1);
        if(fReq.getStatus().equalsIgnoreCase("Rejected")){
            JOptionPane.showMessageDialog(null, "Request is rejected already", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else if(fReq.getStatus().equalsIgnoreCase("Accepted")){
            JOptionPane.showMessageDialog(null, "Request is accepted already", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else if(fReq.getStatus().equalsIgnoreCase("Processed - Sent to Volunteering Head")){
            JOptionPane.showMessageDialog(null, "Request is processed already", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else if(fReq.getStatus().equalsIgnoreCase("Completed")){
            JOptionPane.showMessageDialog(null, "Request is completed already", "Warning", JOptionPane.WARNING_MESSAGE);

        }
        else{

            fReq.setStatus("Rejected");
            //        dist.getFinanceRequestDirectory().addFinanceRequest(fReq);
            JOptionPane.showMessageDialog(null, "Request Rejected!!!");
        }
        populateTable();

    }//GEN-LAST:event_btnRejectActionPerformed

    private void btnCompleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCompleteMouseEntered
        // TODO add your handling code here:
        btnComplete.setBackground(new Color(0,255,204));
        btnComplete.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btnCompleteMouseEntered

    private void btnCompleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCompleteMouseExited
        // TODO add your handling code here:
        btnComplete.setForeground(new Color(0,255,204));
        btnComplete.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnCompleteMouseExited

    private void btnCompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleteActionPerformed
        // TODO add your handling code here:
        int row = tblRequestHistory.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        VolunteerRequest fReq=(VolunteerRequest)tblRequestHistory.getValueAt(row, 1);
        if(fReq.getStatus().equalsIgnoreCase("Rejected")){
            JOptionPane.showMessageDialog(null, "Request is rejected already", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else if(fReq.getStatus().equalsIgnoreCase("Processed - Sent to Volunteering Head")){
            JOptionPane.showMessageDialog(null, "Request is processed already", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else if(fReq.getStatus().equalsIgnoreCase("Completed")){
            JOptionPane.showMessageDialog(null, "Request is completed already", "Warning", JOptionPane.WARNING_MESSAGE);

        }
        else{

            fReq.setStatus("Completed");
//            representative.getVolunteerRequestDirectory().addVolunteerRequest(fReq);
            JOptionPane.showMessageDialog(null, "Request Completed Successfully!!!");
        }
        populateTable();
    }//GEN-LAST:event_btnCompleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnComplete;
    private javax.swing.JButton btnReject;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRequestHistory;
    // End of variables declaration//GEN-END:variables
}
