/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.GOVTExecutive;

import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author rtspi
 */
public class GOVTExecutiveWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form GOVTExecutiveWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Organization organization;
    public GOVTExecutiveWorkAreaJPanel(JPanel userProcessContainer, Ecosystem system,Enterprise enterprise,UserAccount account,Organization organization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.organization = organization;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnManageRationingRequests = new javax.swing.JButton();
        btnManageVolunteerRequests = new javax.swing.JButton();
        rightGOVTExecutiveJPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Government Executive");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        btnManageRationingRequests.setBackground(new java.awt.Color(0, 255, 204));
        btnManageRationingRequests.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnManageRationingRequests.setForeground(new java.awt.Color(255, 255, 255));
        btnManageRationingRequests.setText("Manage Ration Requests");
        btnManageRationingRequests.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManageRationingRequests.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnManageRationingRequestsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnManageRationingRequestsMouseExited(evt);
            }
        });
        btnManageRationingRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageRationingRequestsActionPerformed(evt);
            }
        });

        btnManageVolunteerRequests.setBackground(new java.awt.Color(0, 255, 204));
        btnManageVolunteerRequests.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnManageVolunteerRequests.setForeground(new java.awt.Color(255, 255, 255));
        btnManageVolunteerRequests.setText("Manage Volunteer Requests");
        btnManageVolunteerRequests.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManageVolunteerRequests.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnManageVolunteerRequestsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnManageVolunteerRequestsMouseExited(evt);
            }
        });
        btnManageVolunteerRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageVolunteerRequestsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnManageRationingRequests, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnManageVolunteerRequests, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(20, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(btnManageRationingRequests, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnManageVolunteerRequests, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(62, 62, 62)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(736, Short.MAX_VALUE)))
        );

        rightGOVTExecutiveJPanel.setBackground(new java.awt.Color(255, 255, 255));
        rightGOVTExecutiveJPanel.setLayout(new java.awt.CardLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/government.jpg"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(1024, 750));
        rightGOVTExecutiveJPanel.add(jLabel2, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightGOVTExecutiveJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rightGOVTExecutiveJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageRationingRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageRationingRequestsActionPerformed
        // TODO add your handling code here:
        ManageExecutiveRationRequestsJPanel manageRequestsJPanel = new ManageExecutiveRationRequestsJPanel(rightGOVTExecutiveJPanel, enterprise,userAccount, enterprise.getOrganizationDirectory(), organization);
        rightGOVTExecutiveJPanel.add("manageRequestsJPanel", manageRequestsJPanel);
        CardLayout layout = (CardLayout) rightGOVTExecutiveJPanel.getLayout();
        layout.next(rightGOVTExecutiveJPanel);
    }//GEN-LAST:event_btnManageRationingRequestsActionPerformed

    private void btnManageVolunteerRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageVolunteerRequestsActionPerformed
        // TODO add your handling code here:
        ManageExecutiveVolunteerRequestsJPanel manageUnitRequestsJPanel = new ManageExecutiveVolunteerRequestsJPanel(rightGOVTExecutiveJPanel, enterprise, userAccount, enterprise.getOrganizationDirectory(), organization);
        rightGOVTExecutiveJPanel.add("manageUnitRequestsJPanel", manageUnitRequestsJPanel);
        CardLayout layout = (CardLayout) rightGOVTExecutiveJPanel.getLayout();
        layout.next(rightGOVTExecutiveJPanel);
    }//GEN-LAST:event_btnManageVolunteerRequestsActionPerformed

    private void btnManageRationingRequestsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageRationingRequestsMouseEntered
        // TODO add your handling code here:
        btnManageRationingRequests.setBackground(new Color(0,255,204));
btnManageRationingRequests.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btnManageRationingRequestsMouseEntered

    private void btnManageRationingRequestsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageRationingRequestsMouseExited
        // TODO add your handling code here:
        btnManageRationingRequests.setForeground(new Color(0,255,204));
btnManageRationingRequests.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnManageRationingRequestsMouseExited

    private void btnManageVolunteerRequestsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageVolunteerRequestsMouseEntered
        // TODO add your handling code here:
        btnManageVolunteerRequests.setBackground(new Color(0,255,204));
btnManageVolunteerRequests.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btnManageVolunteerRequestsMouseEntered

    private void btnManageVolunteerRequestsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageVolunteerRequestsMouseExited
        // TODO add your handling code here:
        btnManageVolunteerRequests.setForeground(new Color(0,255,204));
btnManageVolunteerRequests.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnManageVolunteerRequestsMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageRationingRequests;
    private javax.swing.JButton btnManageVolunteerRequests;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel rightGOVTExecutiveJPanel;
    // End of variables declaration//GEN-END:variables
}
