/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.GOVTExecutive;

import UserInterface.BackgroundCheckAdminWorkArea.*;
import Business.Enterprise.Enterprise;
import Business.Executive.Executive;
import Business.HealthMinistryRepresentative.Representative;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.FinanceRequest;
import Business.WorkQueue.RationRequest;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rtspi
 */
public class ManageExecutiveRationRequestsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form manageBGRequestsJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount useraccount;
    private OrganizationDirectory orgDir;
    private Organization org;
     Executive executive;
     Representative representative;
    
    public ManageExecutiveRationRequestsJPanel(JPanel userProcessContainer, Enterprise enterprise, UserAccount useraccount,OrganizationDirectory orgDir, Organization org) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.useraccount = useraccount;
        this.orgDir = orgDir;
        this.org = org;
//        executive = org.getExecutiveDirectory().findUserByUserName(useraccount.getUsername());
        populateRepresentativeComboBox();
        populateTable();
    }
    
    public void populateRepresentativeComboBox(){
        
        representativeJComboBox.removeAllItems();
        for(Organization org1 : orgDir.getOrgList()){
            
            for(Representative ra: org1.getRepresentativeDirectory().getRepresentativeList()){
                
                    representativeJComboBox.addItem(ra);
                
                
            }
            
        }                
    }
    
    public void populateTable(){
        
        DefaultTableModel model = (DefaultTableModel) tblRequestHistory.getModel();
        model.setRowCount(0);
        executive = org.getExecutiveDirectory().findUserByUserName(useraccount.getUsername());

        for(RationRequest req : executive.getRationRequestDirectory().getRationRequestList()){
            System.out.println(req);
            Object[] row = new Object[5];
            row[0] = req.getRequestName();
            row[1] = req;
            row[2] = req.getSizeOfPacket();
            row[3] = req.getUnits();
            row[4] = req.getStatus();
            model.addRow(row);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAccept = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnProcess = new javax.swing.JButton();
        representativeJComboBox = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRequestHistory = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAccept.setBackground(new java.awt.Color(255, 255, 255));
        btnAccept.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnAccept.setForeground(new java.awt.Color(0, 255, 204));
        btnAccept.setText("Accept Request");
        btnAccept.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAccept.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAcceptMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAcceptMouseExited(evt);
            }
        });
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });
        add(btnAccept, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, -1, -1));

        btnReject.setBackground(new java.awt.Color(255, 255, 255));
        btnReject.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnReject.setForeground(new java.awt.Color(0, 255, 204));
        btnReject.setText("Reject Request");
        btnReject.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRejectMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRejectMouseExited(evt);
            }
        });
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });
        add(btnReject, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, -1, -1));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel1.setText("Assign Representative:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, 140, 20));

        btnProcess.setBackground(new java.awt.Color(255, 255, 255));
        btnProcess.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnProcess.setForeground(new java.awt.Color(0, 255, 204));
        btnProcess.setText("Process Request");
        btnProcess.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProcess.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProcessMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProcessMouseExited(evt);
            }
        });
        btnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessActionPerformed(evt);
            }
        });
        add(btnProcess, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 520, -1, -1));

        representativeJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                representativeJComboBoxActionPerformed(evt);
            }
        });
        add(representativeJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 390, 180, -1));

        tblRequestHistory.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        tblRequestHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Request Name", "Type of Packet", "Size of Packet", "# of Units", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblRequestHistory);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 110, 720, 110));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel2.setText("Manage Ration Requests");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessActionPerformed
        // TODO add your handling code here:
        int row = tblRequestHistory.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        RationRequest fReq=(RationRequest)tblRequestHistory.getValueAt(row, 1);
        if(fReq.getStatus().equalsIgnoreCase("Rejected")){
            JOptionPane.showMessageDialog(null, "Request is rejected already", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else if(fReq.getStatus().equalsIgnoreCase("Processed - Sent to Government Representative")){
            JOptionPane.showMessageDialog(null, "Request is processed already", "Warning", JOptionPane.WARNING_MESSAGE);
        }
         else if(fReq.getStatus().equalsIgnoreCase("Completed")){
            JOptionPane.showMessageDialog(null, "Request is completed already", "Warning", JOptionPane.WARNING_MESSAGE);

        }
        else{
        
        
        fReq.setStatus("Processed - Sent to Government Representative");
        representative.getRationRequestDirectory().addRationRequest(fReq);
        JOptionPane.showMessageDialog(null, "Request Processed Successfully!!!");
        } 
        populateTable();
        
    }//GEN-LAST:event_btnProcessActionPerformed

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        // TODO add your handling code here:
        int row = tblRequestHistory.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        RationRequest fReq=(RationRequest)tblRequestHistory.getValueAt(row, 1);
        if(fReq.getStatus().equalsIgnoreCase("Rejected")){
            JOptionPane.showMessageDialog(null, "Request is rejected already", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else if(fReq.getStatus().equalsIgnoreCase("Accepted")){
            JOptionPane.showMessageDialog(null, "Request is already accepted", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else if(fReq.getStatus().equalsIgnoreCase("Processed - Sent to Government Representative")){
            JOptionPane.showMessageDialog(null, "Request is processed already", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else if(fReq.getStatus().equalsIgnoreCase("Completed")){
            JOptionPane.showMessageDialog(null, "Request is completed already", "Warning", JOptionPane.WARNING_MESSAGE);

        }
        
        else{
        
//        FinanceRequest fReq=(FinanceRequest)tblRequests.getValueAt(row, 1);
        fReq.setStatus("Accepted");
        JOptionPane.showMessageDialog(null, "Request Accepted successfully!!!");
        } 
        populateTable();
        
        
        
    }//GEN-LAST:event_btnAcceptActionPerformed

    private void btnAcceptMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcceptMouseEntered
        // TODO add your handling code here:
        btnAccept.setBackground(new Color(0,255,204));
        btnAccept.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btnAcceptMouseEntered

    private void btnAcceptMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcceptMouseExited
        // TODO add your handling code here:
        btnAccept.setForeground(new Color(0,255,204));
        btnAccept.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnAcceptMouseExited

    private void btnRejectMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRejectMouseEntered
        // TODO add your handling code here:
        btnReject.setBackground(new Color(0,255,204));
        btnReject.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btnRejectMouseEntered

    private void btnRejectMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRejectMouseExited
        // TODO add your handling code here:
        btnReject.setForeground(new Color(0,255,204));
        btnReject.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnRejectMouseExited

    private void btnProcessMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProcessMouseEntered
        // TODO add your handling code here:
        btnProcess.setBackground(new Color(0,255,204));
        btnProcess.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btnProcessMouseEntered

    private void btnProcessMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProcessMouseExited
        // TODO add your handling code here:
        btnProcess.setForeground(new Color(0,255,204));
        btnProcess.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnProcessMouseExited

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
        // TODO add your handling code here:
        int row = tblRequestHistory.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        RationRequest fReq=(RationRequest)tblRequestHistory.getValueAt(row, 1);
        if(fReq.getStatus().equalsIgnoreCase("Rejected")){
            JOptionPane.showMessageDialog(null, "Request is rejected already", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else if(fReq.getStatus().equalsIgnoreCase("Accepted")){
            JOptionPane.showMessageDialog(null, "Request is accepted already", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else if(fReq.getStatus().equalsIgnoreCase("Processed - Sent to Government Representative")){
            JOptionPane.showMessageDialog(null, "Request is processed already", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else if(fReq.getStatus().equalsIgnoreCase("Completed")){
            JOptionPane.showMessageDialog(null, "Request is completed already", "Warning", JOptionPane.WARNING_MESSAGE);

        }
        else{
        
        
        fReq.setStatus("Rejected");
//        dist.getFinanceRequestDirectory().addFinanceRequest(fReq);
        JOptionPane.showMessageDialog(null, "Request Rejected!!!");
        } 
        populateTable();
        
        
    }//GEN-LAST:event_btnRejectActionPerformed

    private void representativeJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_representativeJComboBoxActionPerformed
        // TODO add your handling code here:
        representative = (Representative) representativeJComboBox.getSelectedItem();
    }//GEN-LAST:event_representativeJComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnProcess;
    private javax.swing.JButton btnReject;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox representativeJComboBox;
    private javax.swing.JTable tblRequestHistory;
    // End of variables declaration//GEN-END:variables
}
