/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.FinanceAdminWorkArea;

import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author rtspi
 */
public class FinanceAdminWorkAreaJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    Enterprise enterprise;
    UserAccount useraccount;
    Organization org;
    Ecosystem system;

    /**
     * Creates new form FinanceAdminWorkAreaJPanel
     */
    public FinanceAdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount useraccount, Organization org, Enterprise enterprise, Ecosystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.useraccount = useraccount;
        this.enterprise = enterprise;
        this.system = system;
        this.org = org;
//        manageOrganization();
    }

    private void manageOrganization(){
       
        FinanceAdminManageOrganizationJPanel manageOrganizationJPanel = new FinanceAdminManageOrganizationJPanel(rightFinanceAdminJPanel, enterprise, enterprise.getOrganizationDirectory());
        rightFinanceAdminJPanel.add("FinanceAdminManageOrganizationJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) rightFinanceAdminJPanel.getLayout();
        layout.next(rightFinanceAdminJPanel);
    }
        private void manageEmployee(){
        
        
        FinanceAdminManageEmployeesJPanel manageEmployeeJPanel = new FinanceAdminManageEmployeesJPanel(rightFinanceAdminJPanel, enterprise, enterprise.getOrganizationDirectory());
        rightFinanceAdminJPanel.add("FinanceAdminManageEmployeeJPanel", manageEmployeeJPanel);
        CardLayout layout = (CardLayout) rightFinanceAdminJPanel.getLayout();
        layout.next(rightFinanceAdminJPanel);
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        financeAdminJPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        btnManageOrg = new javax.swing.JButton();
        btnManageStaff = new javax.swing.JButton();
        rightFinanceAdminJPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.MatteBorder(null));

        financeAdminJPanel.setBackground(new java.awt.Color(255, 255, 255));
        financeAdminJPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        financeAdminJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FINANCE ADMIN SYSTEM");
        financeAdminJPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 210, 30));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        financeAdminJPanel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 210, 10));

        btnManageOrg.setBackground(new java.awt.Color(255, 255, 255));
        btnManageOrg.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnManageOrg.setForeground(new java.awt.Color(0, 255, 204));
        btnManageOrg.setText("Manage Organization");
        btnManageOrg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManageOrg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnManageOrgMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnManageOrgMouseExited(evt);
            }
        });
        btnManageOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageOrgActionPerformed(evt);
            }
        });
        financeAdminJPanel.add(btnManageOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 170, 40));

        btnManageStaff.setBackground(new java.awt.Color(255, 255, 255));
        btnManageStaff.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnManageStaff.setForeground(new java.awt.Color(0, 255, 204));
        btnManageStaff.setText("Manage Staff");
        btnManageStaff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManageStaff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnManageStaffMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnManageStaffMouseExited(evt);
            }
        });
        btnManageStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageStaffActionPerformed(evt);
            }
        });
        financeAdminJPanel.add(btnManageStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 170, 40));

        rightFinanceAdminJPanel.setBackground(new java.awt.Color(255, 255, 255));
        rightFinanceAdminJPanel.setLayout(new java.awt.CardLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/finance-cyber-security.png"))); // NOI18N
        rightFinanceAdminJPanel.add(jLabel3, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(financeAdminJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rightFinanceAdminJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1046, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(financeAdminJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE)
            .addComponent(rightFinanceAdminJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageOrgActionPerformed
        // TODO add your handling code here:

       manageOrganization();
    }//GEN-LAST:event_btnManageOrgActionPerformed

    private void btnManageStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageStaffActionPerformed
        // TODO add your handling code here:
        manageEmployee();
        
    }//GEN-LAST:event_btnManageStaffActionPerformed

    private void btnManageOrgMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageOrgMouseEntered
        // TODO add your handling code here:
        btnManageOrg.setBackground(new Color(0,255,204));
        btnManageOrg.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btnManageOrgMouseEntered

    private void btnManageOrgMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageOrgMouseExited
        // TODO add your handling code here:
        btnManageOrg.setForeground(new Color(0,255,204));
        btnManageOrg.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnManageOrgMouseExited

    private void btnManageStaffMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageStaffMouseEntered
        // TODO add your handling code here:
        btnManageStaff.setBackground(new Color(0,255,204));
        btnManageStaff.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btnManageStaffMouseEntered

    private void btnManageStaffMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageStaffMouseExited
        // TODO add your handling code here:
        btnManageStaff.setForeground(new Color(0,255,204));
        btnManageStaff.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnManageStaffMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundCheckJPanel;
    private javax.swing.JButton btnManageOrg;
    private javax.swing.JButton btnManageRequests;
    private javax.swing.JButton btnManageStaff;
    private javax.swing.JPanel financeAdminJPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel rightFinanceAdminJPanel;
    // End of variables declaration//GEN-END:variables
}
