/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.VolunteersWorkArea;

import Business.Ecosystem;
import UserInterface.RationingFacilitatorWorkArea.*;
import Business.Enterprise.Enterprise;
import Business.Executive.Executive;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.UserAccount.UserAccount;
import Business.VolunteeringHead.VolunteeringHead;
import Business.WorkQueue.VolunteerRequest;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rtspi
 */
public class VolunteeringHeadUnitRequestsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form VolunteeringHeadUnitRequestsJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount useraccount;
    private OrganizationDirectory orgDir;
    private Ecosystem system;
    private Executive executive;
    Organization org;
    private VolunteeringHead volunteer;
   
    private VolunteerRequest volunteerRequest;
    public VolunteeringHeadUnitRequestsJPanel(JPanel userProcessContainer, Enterprise enterprise, UserAccount useraccount,OrganizationDirectory orgDir, Ecosystem system, Organization org) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.useraccount = useraccount;
        this.orgDir = orgDir;
        this.system = system;
        this.org = org;
        volunteer = org.getVolunteeringHeadDirectory().findUserByUserName(useraccount.getUsername());
        populateExecutiveComboBox();
        populateVolunteerTypeComboBox();
        populateTable();
    }
    
    public void populateVolunteerTypeComboBox(){
        volunteerTypeJComboBox.removeAllItems();
        volunteerTypeJComboBox.addItem("Delivery Agent Volunteer");
        volunteerTypeJComboBox.addItem("On Ground Volunteer");
        
    }
        public void populateExecutiveComboBox(){
        executiveJComboBox.removeAllItems();
        for(Network net: system.getNetworkList()){
        for(Enterprise ent : net.getEnterpriseDirectory().getEntList()){
            for(Organization org : ent.getOrganizationDirectory().getOrgList()){
                if(org.getType().getValue().equalsIgnoreCase("Executive Organization")){
                    for(Executive ex: org.getExecutiveDirectory().getExecutiveList()){
                
                    executiveJComboBox.addItem(ex);
                    }
                }
                
            }  
                }
                  
    }
    }
        
        public void populateTable(){
            
            DefaultTableModel model = (DefaultTableModel) tblRequestHistory.getModel();
        model.setRowCount(0);
//        executive = (Executive) executiveJComboBox.getSelectedItem();
        for(VolunteerRequest req : volunteer.getVolunteerRequestDirectory().getVolunteerRequestList()){
            System.out.println(req);
            Object[] row = new Object[5];
            row[0] = req.getRequestName();
            row[1] = req.getUnits();
            row[2] = req.getTypeOfVolunteer();
            row[3] = req.getDate();
            row[4] = req.getStatus();
            model.addRow(row);
            
        }
            
        }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRequestHistory = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnRequestVolunteer = new javax.swing.JButton();
        executiveJComboBox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNumberVolunteer = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        volunteerTypeJComboBox = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));

        tblRequestHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Request Name", "Number of Volunteers", "Type of Volunteer", "Request Date", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblRequestHistory);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Request History");

        btnRequestVolunteer.setBackground(new java.awt.Color(255, 255, 255));
        btnRequestVolunteer.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnRequestVolunteer.setForeground(new java.awt.Color(0, 255, 204));
        btnRequestVolunteer.setText("Request Volunteer");
        btnRequestVolunteer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRequestVolunteer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRequestVolunteerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRequestVolunteerMouseExited(evt);
            }
        });
        btnRequestVolunteer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestVolunteerActionPerformed(evt);
            }
        });

        executiveJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executiveJComboBoxActionPerformed(evt);
            }
        });

        jLabel5.setText("Assign Government Executive:");

        jLabel2.setText("Number of Volunteers:");

        jLabel3.setText("Type of Volunteer:");

        volunteerTypeJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(executiveJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnRequestVolunteer)
                                .addComponent(txtNumberVolunteer)
                                .addComponent(volunteerTypeJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(310, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNumberVolunteer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(volunteerTypeJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(executiveJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94)
                .addComponent(btnRequestVolunteer)
                .addContainerGap(227, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void executiveJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executiveJComboBoxActionPerformed
        // TODO add your handling code here:
        executive = (Executive) executiveJComboBox.getSelectedItem();
    }//GEN-LAST:event_executiveJComboBoxActionPerformed

    private void btnRequestVolunteerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestVolunteerActionPerformed
        // TODO add your handling code here:
        
        String units = txtNumberVolunteer.getText();
        String type = (String) volunteerTypeJComboBox.getSelectedItem();
        executive = (Executive) executiveJComboBox.getSelectedItem();
        if(units.equalsIgnoreCase("") || units.matches("[A-Za-z]+")){
            JOptionPane.showMessageDialog(null, "Please enter valid number of units", "Warning", JOptionPane.PLAIN_MESSAGE);
            txtNumberVolunteer.setText("");
        }
        else{
            volunteerRequest = new VolunteerRequest(type);
        volunteerRequest.setUnits(units);
        volunteerRequest.setTypeOfVolunteer(type);
        volunteerRequest.setStatus("Sent to Government Executive");
        executive.getVolunteerRequestDirectory().addVolunteerRequest(volunteerRequest);
        volunteer.getVolunteerRequestDirectory().addVolunteerRequest(volunteerRequest);
        JOptionPane.showMessageDialog(null, "Request Sent Successfully", "Success", JOptionPane.PLAIN_MESSAGE);
        populateTable();
        txtNumberVolunteer.setText("");
        }
        
        
        
        
    }//GEN-LAST:event_btnRequestVolunteerActionPerformed

    private void btnRequestVolunteerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRequestVolunteerMouseEntered
        // TODO add your handling code here:
        btnRequestVolunteer.setBackground(new Color(0,255,204));
        btnRequestVolunteer.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btnRequestVolunteerMouseEntered

    private void btnRequestVolunteerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRequestVolunteerMouseExited
        // TODO add your handling code here:
        btnRequestVolunteer.setForeground(new Color(0,255,204));
        btnRequestVolunteer.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnRequestVolunteerMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRequestVolunteer;
    private javax.swing.JComboBox executiveJComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRequestHistory;
    private javax.swing.JTextField txtNumberVolunteer;
    private javax.swing.JComboBox<String> volunteerTypeJComboBox;
    // End of variables declaration//GEN-END:variables
}
