/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.GovernmentAdminWorkArea;

import UserInterface.FinanceAdminWorkArea.*;
import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author juhip
 */
public class GOVTAdminWorkAreaJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    Enterprise enterprise;
    Ecosystem system;
    UserAccount useraccount;
    Organization organization;

    /**
     * Creates new form FinanceAdminWorkAreaJPanel
     */
    public GOVTAdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount useraccount, Organization org, Enterprise enterprise, Ecosystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.system = system;
        this.useraccount = useraccount;
        this.organization = org;
//        manageOrganization();
    }

    private void manageOrganization(){
        
        GOVTAdminManageOrganizationJPanel manageOrganizationJPanel = new GOVTAdminManageOrganizationJPanel(rightGovernmentAdminJPanel, enterprise, enterprise.getOrganizationDirectory());
        rightGovernmentAdminJPanel.add("GOVTAdminManageOrganizationJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) rightGovernmentAdminJPanel.getLayout();
        layout.next(rightGovernmentAdminJPanel);
    }
        private void manageEmployee(){
        
        
        GOVTAdminManageEmployeesJPanel manageEmployeeJPanel = new GOVTAdminManageEmployeesJPanel(rightGovernmentAdminJPanel, enterprise,enterprise.getOrganizationDirectory());
        rightGovernmentAdminJPanel.add("GOVTAdminManageEmployeeJPanel", manageEmployeeJPanel);
        CardLayout layout = (CardLayout) rightGovernmentAdminJPanel.getLayout();
        layout.next(rightGovernmentAdminJPanel);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        governmentAdminJPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnManageOrg = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        btnManageStaff = new javax.swing.JButton();
        rightGovernmentAdminJPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.MatteBorder(null));

        governmentAdminJPanel.setBackground(new java.awt.Color(255, 255, 255));
        governmentAdminJPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        governmentAdminJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GOVERNMENT ADMIN SYSTEM");
        governmentAdminJPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 240, 30));

        btnManageOrg.setBackground(new java.awt.Color(255, 255, 255));
        btnManageOrg.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnManageOrg.setForeground(new java.awt.Color(0, 255, 204));
        btnManageOrg.setText("Manage Organization");
        btnManageOrg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManageOrg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnManageOrgMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnManageOrgMouseExited(evt);
            }
        });
        btnManageOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageOrgActionPerformed(evt);
            }
        });
        governmentAdminJPanel.add(btnManageOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 170, 40));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        governmentAdminJPanel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 260, 10));

        btnManageStaff.setBackground(new java.awt.Color(255, 255, 255));
        btnManageStaff.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnManageStaff.setForeground(new java.awt.Color(0, 255, 204));
        btnManageStaff.setText("Manage Staff");
        btnManageStaff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManageStaff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnManageStaffMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnManageStaffMouseExited(evt);
            }
        });
        btnManageStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageStaffActionPerformed(evt);
            }
        });
        governmentAdminJPanel.add(btnManageStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 170, 40));

        rightGovernmentAdminJPanel.setBackground(new java.awt.Color(255, 255, 255));
        rightGovernmentAdminJPanel.setLayout(new java.awt.CardLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/government admin.jpg"))); // NOI18N
        rightGovernmentAdminJPanel.add(jLabel2, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(governmentAdminJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightGovernmentAdminJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1016, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(governmentAdminJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
            .addComponent(rightGovernmentAdminJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageOrgMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageOrgMouseEntered
        // TODO add your handling code here:
        btnManageOrg.setBackground(new Color(0,255,204));
        btnManageOrg.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btnManageOrgMouseEntered

    private void btnManageOrgMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageOrgMouseExited
        // TODO add your handling code here:
        btnManageOrg.setForeground(new Color(0,255,204));
        btnManageOrg.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnManageOrgMouseExited

    private void btnManageOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageOrgActionPerformed
        // TODO add your handling code here:

        manageOrganization();
    }//GEN-LAST:event_btnManageOrgActionPerformed

    private void btnManageStaffMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageStaffMouseEntered
        // TODO add your handling code here:
        btnManageStaff.setBackground(new Color(0,255,204));
        btnManageStaff.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btnManageStaffMouseEntered

    private void btnManageStaffMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageStaffMouseExited
        // TODO add your handling code here:
        btnManageStaff.setForeground(new Color(0,255,204));
        btnManageStaff.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnManageStaffMouseExited

    private void btnManageStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageStaffActionPerformed
        // TODO add your handling code here:
        manageEmployee();

    }//GEN-LAST:event_btnManageStaffActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageOrg;
    private javax.swing.JButton btnManageStaff;
    private javax.swing.JPanel governmentAdminJPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel rightGovernmentAdminJPanel;
    // End of variables declaration//GEN-END:variables
}
