/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ExpertTherapistRole;



import UserInterface.GeneralTherapistRole.*;
import UserInterface.OnlineReceptionistRole.*;
import UserInterface.User.*;
import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.ExpertTherapist.ExpertTherapist;
import Business.GeneralTherapist.GeneralTherapist;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.Role.GeneralTherapistRole;
import Business.TestDefiner.Test;
import Business.TestDefiner.TestDefiner;
import Business.User.User;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.Request;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juhip
 */
public class RequestDetailsExpertJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEmpJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise ent;
    private UserAccount userAccount;
    private Organization org;
    private Ecosystem system;
    private Request request;
    private Organization organi;
    private Boolean flagTherapist = false;
    private ArrayList<Test> selectedTest =new ArrayList<>();
    private ArrayList<Test> uniqueTests =new ArrayList<>();
    private ArrayList<Test> testSample = new ArrayList<>();
    DateFormat formatter = new SimpleDateFormat("MM/dd/yyyy");
       
    public RequestDetailsExpertJPanel(JPanel userProcessContainer, Ecosystem system, UserAccount userAccount, Request request, Organization org, Enterprise ent) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.system = system;
        this.ent=ent;
        this.org = org;
        this.request = request;
        populateData();
//        hideButtons();
        changeButtons();
        viewReportButton();
        tableJPanel.setVisible(false);
    }
     public class HeaderColor extends DefaultTableCellRenderer {
        public HeaderColor() {
            setOpaque(true);
        }
        public Component getTableCellRendererComponent(JTable table, Object value, boolean selected, boolean focused, int row, int column) {
            super.getTableCellRendererComponent(table, value, selected, focused, row, column);         
//           setBackground(new java.awt.Color(74,122,193));
            return this;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblDoctorslist1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblQuestion1 = new javax.swing.JLabel();
        lblQuestion2 = new javax.swing.JLabel();
        lblQuestion3 = new javax.swing.JLabel();
        lblQuestion4 = new javax.swing.JLabel();
        lblQuestion5 = new javax.swing.JLabel();
        lblQuestion6 = new javax.swing.JLabel();
        lblQuestion7 = new javax.swing.JLabel();
        lblQuestion8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        btnAssignTest = new javax.swing.JButton();
        btnManagePrescription = new javax.swing.JButton();
        tableJPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        selectedTestTable = new javax.swing.JTable();
        btnSubmit = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        availableTable = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnTestReporter = new javax.swing.JButton();
        btnViewReport = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        lblDoctorslist1.setFont(new java.awt.Font(".SF NS Text", 1, 18)); // NOI18N
        lblDoctorslist1.setText("Request Details");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("To begin, please select why you thought about getting help from a provider:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("I'm looking for a therapist that will...");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Have you been to a therapist or psychiatrist before?");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("How Would you rate your sleeping habbits?");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("How would you rate your current physical health?");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("What gender do you identify with?");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("What gender would you prefer in a provider?");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("What state do you live in?");

        lblQuestion1.setText("To begin, please select why you thought about getting help from a provider:");

        lblQuestion2.setText("I'm looking for a therapist that will...");

        lblQuestion3.setText("Have you been to a therapist or psychiatrist before?");

        lblQuestion4.setText("How Would you rate your sleeping habbits?");

        lblQuestion5.setText("How would you rate your current physical health?");

        lblQuestion6.setText("What gender do you identify with?");

        lblQuestion7.setText("What gender would you prefer in a provider?");

        lblQuestion8.setText("What state do you live in?");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Status");

        lblStatus.setText("Status");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(lblDoctorslist1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblQuestion1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblQuestion8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblQuestion7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblQuestion6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblQuestion5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblQuestion4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblQuestion3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                                        .addComponent(lblQuestion2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblDoctorslist1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuestion1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblQuestion2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblQuestion3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblQuestion4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblQuestion5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblQuestion6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblQuestion7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblQuestion8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 840, 360));

        btnAssignTest.setBackground(new java.awt.Color(255, 255, 255));
        btnAssignTest.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnAssignTest.setForeground(new java.awt.Color(0, 255, 204));
        btnAssignTest.setText("Assign Tests");
        btnAssignTest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAssignTest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAssignTestMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAssignTestMouseExited(evt);
            }
        });
        btnAssignTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignTestActionPerformed(evt);
            }
        });
        add(btnAssignTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, 170, -1));

        btnManagePrescription.setBackground(new java.awt.Color(255, 255, 255));
        btnManagePrescription.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnManagePrescription.setForeground(new java.awt.Color(0, 255, 204));
        btnManagePrescription.setText("Manage Prescription");
        btnManagePrescription.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManagePrescription.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnManagePrescriptionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnManagePrescriptionMouseExited(evt);
            }
        });
        btnManagePrescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagePrescriptionActionPerformed(evt);
            }
        });
        add(btnManagePrescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 170, -1));

        tableJPanel.setBackground(new java.awt.Color(255, 255, 255));

        selectedTestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Selected Tests"
            }
        ));
        jScrollPane1.setViewportView(selectedTestTable);

        btnSubmit.setBackground(new java.awt.Color(255, 255, 255));
        btnSubmit.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(0, 255, 204));
        btnSubmit.setText("Submit");
        btnSubmit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSubmitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSubmitMouseExited(evt);
            }
        });
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        availableTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Available Tests"
            }
        ));
        jScrollPane2.setViewportView(availableTable);

        btnAdd.setBackground(new java.awt.Color(255, 255, 255));
        btnAdd.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(0, 255, 204));
        btnAdd.setText("Add");
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddMouseExited(evt);
            }
        });
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tableJPanelLayout = new javax.swing.GroupLayout(tableJPanel);
        tableJPanel.setLayout(tableJPanelLayout);
        tableJPanelLayout.setHorizontalGroup(
            tableJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableJPanelLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addComponent(btnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(btnSubmit))
        );
        tableJPanelLayout.setVerticalGroup(
            tableJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableJPanelLayout.createSequentialGroup()
                .addGroup(tableJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tableJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(tableJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(tableJPanelLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(btnSubmit)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tableJPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAdd)
                .addGap(63, 63, 63))
        );

        add(tableJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 820, 150));

        btnTestReporter.setBackground(new java.awt.Color(255, 255, 255));
        btnTestReporter.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnTestReporter.setForeground(new java.awt.Color(0, 255, 204));
        btnTestReporter.setText("Assign Test Reporter");
        btnTestReporter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTestReporter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTestReporterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTestReporterMouseExited(evt);
            }
        });
        btnTestReporter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestReporterActionPerformed(evt);
            }
        });
        add(btnTestReporter, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, 220, -1));

        btnViewReport.setBackground(new java.awt.Color(255, 255, 255));
        btnViewReport.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnViewReport.setForeground(new java.awt.Color(0, 255, 204));
        btnViewReport.setText("View Reports");
        btnViewReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViewReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnViewReportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnViewReportMouseExited(evt);
            }
        });
        btnViewReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewReportActionPerformed(evt);
            }
        });
        add(btnViewReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 390, 180, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnManagePrescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagePrescriptionActionPerformed
        // TODO add your handling code here:
            ManagePrescriptionJPanel managePrescriptionJPanel=new ManagePrescriptionJPanel(userProcessContainer,system, userAccount,org, ent, request);
            userProcessContainer.add("managePrescriptionJPanel", managePrescriptionJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnManagePrescriptionActionPerformed

    private void btnAssignTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignTestActionPerformed
        // TODO add your handling code here:
        tableJPanel.setVisible(true);
        populateAvailablTable(); 
    }//GEN-LAST:event_btnAssignTestActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        for(Test test: selectedTest){
            request.getUserAssignedTestDirectory().addTest(test);
            JOptionPane.showMessageDialog(null, "Tests Assigned Successfully!");
        }
        tableJPanel.setVisible(false);
            
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        
         int row = availableTable.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }else{
            Test test = (Test)availableTable.getValueAt(row, 0);
            if(!selectedTest.contains(test)){
                selectedTest.add(test);
                populateSelectedTable();
            }else{
            JOptionPane.showMessageDialog(null, "Test Already added, please try again!", "Warning", JOptionPane.WARNING_MESSAGE);
            }
            
            
        } 
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnTestReporterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestReporterActionPerformed
        // TODO add your handling code here:
        if(request.getTestReporter()==null){
            AssignTestReporterRequestDetailsExpertJPanel assignReporter=new AssignTestReporterRequestDetailsExpertJPanel(userProcessContainer,system, userAccount,request, org, ent);
        userProcessContainer.add("assignReporter", assignReporter);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        }else{
        JOptionPane.showMessageDialog(null, "Test Reporter Already assigned, please try again!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_btnTestReporterActionPerformed

    private void btnViewReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewReportActionPerformed
        // TODO add your handling code here:
            ViewReportTestsJPanel managePrescriptionJPanel=new ViewReportTestsJPanel(userProcessContainer,system, userAccount,ent, org, request);
            userProcessContainer.add("managePrescriptionJPanel", managePrescriptionJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewReportActionPerformed

    private void btnManagePrescriptionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManagePrescriptionMouseEntered
        // TODO add your handling code here:
        btnManagePrescription.setBackground(new Color(0,255,204));
        btnManagePrescription.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btnManagePrescriptionMouseEntered

    private void btnManagePrescriptionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManagePrescriptionMouseExited
        // TODO add your handling code here:
        btnManagePrescription.setForeground(new Color(0,255,204));
        btnManagePrescription.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnManagePrescriptionMouseExited

    private void btnAssignTestMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAssignTestMouseEntered
        // TODO add your handling code here:
        btnAssignTest.setBackground(new Color(0,255,204));
        btnAssignTest.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btnAssignTestMouseEntered

    private void btnAssignTestMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAssignTestMouseExited
        // TODO add your handling code here:
        btnAssignTest.setForeground(new Color(0,255,204));
        btnAssignTest.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnAssignTestMouseExited

    private void btnTestReporterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTestReporterMouseEntered
        // TODO add your handling code here:
        btnTestReporter.setBackground(new Color(0,255,204));
        btnTestReporter.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btnTestReporterMouseEntered

    private void btnTestReporterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTestReporterMouseExited
        // TODO add your handling code here:
        btnTestReporter.setForeground(new Color(0,255,204));
        btnTestReporter.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnTestReporterMouseExited

    private void btnViewReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewReportMouseEntered
        // TODO add your handling code here:
        btnViewReport.setBackground(new Color(0,255,204));
        btnViewReport.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btnViewReportMouseEntered

    private void btnViewReportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewReportMouseExited
        // TODO add your handling code here:
        btnViewReport.setForeground(new Color(0,255,204));
        btnViewReport.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnViewReportMouseExited

    private void btnAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseEntered
        // TODO add your handling code here:
        btnAdd.setBackground(new Color(0,255,204));
        btnAdd.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btnAddMouseEntered

    private void btnAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseExited
        // TODO add your handling code here:
        btnAdd.setForeground(new Color(0,255,204));
        btnAdd.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnAddMouseExited

    private void btnSubmitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitMouseEntered
        // TODO add your handling code here:
        btnSubmit.setBackground(new Color(0,255,204));
btnSubmit.setForeground(new Color(255,255,255)); 
    }//GEN-LAST:event_btnSubmitMouseEntered

    private void btnSubmitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitMouseExited
        // TODO add your handling code here:
        btnSubmit.setForeground(new Color(0,255,204));
btnSubmit.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnSubmitMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable availableTable;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAssignTest;
    private javax.swing.JButton btnManagePrescription;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnTestReporter;
    private javax.swing.JButton btnViewReport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDoctorslist1;
    private javax.swing.JLabel lblQuestion1;
    private javax.swing.JLabel lblQuestion2;
    private javax.swing.JLabel lblQuestion3;
    private javax.swing.JLabel lblQuestion4;
    private javax.swing.JLabel lblQuestion5;
    private javax.swing.JLabel lblQuestion6;
    private javax.swing.JLabel lblQuestion7;
    private javax.swing.JLabel lblQuestion8;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTable selectedTestTable;
    private javax.swing.JPanel tableJPanel;
    // End of variables declaration//GEN-END:variables
    public void populateData(){
    lblQuestion1.setText(request.getReasonForTreatment());
    lblQuestion2.setText(request.getTherapistRequired());
    lblQuestion3.setText(request.getIfPreviousPsychiatrist());
    lblQuestion4.setText(request.getSleepingHabbit());
    lblQuestion5.setText(request.getCurrentPhysicalHealth());
    lblQuestion6.setText(request.getGender());
    lblQuestion7.setText(request.getPreferedPsychiatristGender());
    lblQuestion8.setText(request.getState());
    lblStatus.setText(request.getStatus());
    }
    
    public void hideButtons(){
    
        if(request.getExprtTherapist()!= null){
            btnAssignTest.setVisible(false);
            btnManagePrescription.setVisible(false);
        }
    }
    
//    public void populateComboBox(){
//        for(Network net: system.getNetworkList()){
//            if(net.getName().equalsIgnoreCase(request.getUser().getNetwork().getName())){
//                   for(Enterprise ent: net.getEnterpriseDirectory().getEntList()){
//            if(ent.getEnterpriseType().getValue().equalsIgnoreCase("MedicalProfessionalsEnterprise")){
//                for(Organization org: ent.getOrganizationDirectory().getOrgList()){
//                    organizationComboBox.addItem(org);
//                }
//            }
//        }
//            }
//        }
//    }
    
        public void populateAvailablTable(){
             DefaultTableModel model = (DefaultTableModel) availableTable.getModel();
            model.setRowCount(0);
            uniqueTests.clear();
            for(Network netwrk:system.getNetworkList()){
                for(Enterprise ent:netwrk.getEnterpriseDirectory().getEntList()){
                    if(ent.getEnterpriseType().getValue().equalsIgnoreCase("TestProviderEnterprise")){
                        for(Organization orga: ent.getOrganizationDirectory().getOrgList()){
                            if(orga.getType().getValue().equalsIgnoreCase("Test Definer")){
                                for(TestDefiner testdef: orga.getTestDefinerDirectory().getTestDefinerList()){
                                    for(Test test: testdef.getTestDirectory().getTestList()){        
//                                        if(!uniqueTests.contains(test)){
//                                            uniqueTests.add(test);
//                                        }
                                           if(uniqueTests.size()==0){
                                           uniqueTests.add(test);
                                           } else {
                                                    testSample = (ArrayList<Test>)uniqueTests.clone();
                                                     for(Test t: testSample){
                                                     if(!t.getTestName().equalsIgnoreCase(test.getTestName())){
                                                         uniqueTests.add(test);
                                                     }
                                                     }
                                           }
                                    }
                                }
                            }
                        }
                    }
                }
                }
            
            for(Test test: uniqueTests){
                Object[] row = new Object[1];
                         row[0] = test;
                         model.addRow(row);
            }
        }  
        
        
        public void populateSelectedTable(){
             DefaultTableModel model = (DefaultTableModel) selectedTestTable.getModel();
            model.setRowCount(0);
                for(Test test: selectedTest){
                     Object[] row = new Object[1];
                     row[0] = test;
                     model.addRow(row);
                }
                }
        public void changeButtons(){
            if(request.getUserAssignedTestDirectory().getTestList().size()!=0){
                btnAssignTest.setVisible(false);
            }
        }
        public  void viewReportButton(){
        if(request.getTestComment()==null){
            btnViewReport.setVisible(false);
        }
        }
}